/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thoughtworks.examonline;

import static org.junit.Assert.assertNotNull;

import com.thoughtworks.examonline.Application;
import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Application classUnderTest = new Application();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
