/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thoughtworks.examonline;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

/**
 * @author gitqh
 */
@SpringBootApplication
@EnableScheduling
@SuppressWarnings({"PMD", "checkstyle:hideutilityclassconstructor"})
public class Application {
    public static void main(final String[] args) {
        SpringApplication.run(com.thoughtworks.examonline.Application.class, args);
    }
}
